"""Email notification service for NeuroSentinel AI.

Sends EEG report completion notifications with the clinical PDF attached.
Supports Resend API (preferred) or SMTP fallback.
"""
from __future__ import annotations

import base64
import logging
import smtplib
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Any

import httpx

logger = logging.getLogger(__name__)

# ─── Email templates ───────────────────────────────────────────────

_APP_URL = "https://neurosentinel.vercel.app"

_SUBJECT_SEIZURE = "NeuroSentinel AI — Seizure Activity Detected in {filename}"
_SUBJECT_NO_SEIZURE = "NeuroSentinel AI — No Seizure Activity Detected in {filename}"


def _build_patient_email(report: dict[str, Any], filename: str) -> str:
    result = report.get("result_label", "Unknown")
    risk = report.get("risk_level", "Unknown")
    event_count = report.get("event_count", 0) or 0
    confidence = report.get("confidence_score")
    confidence_text = f"{confidence:.1f}%" if isinstance(confidence, (int, float)) else "unknown"
    seizure_detected = result.lower() == "seizure detected" or (isinstance(event_count, int) and event_count > 0)

    if seizure_detected:
        opening = (
            f"Your EEG recording \"{filename}\" has been analysed by NeuroSentinel AI. "
            f"The analysis has detected seizure-like activity — {event_count} segment(s) were flagged "
            f"with an overall risk level of {risk} and model confidence of {confidence_text}."
        )
        action = (
            "We recommend sharing this report with your healthcare provider or neurologist as soon as possible. "
            "Please do not make any changes to your medication or treatment without consulting your doctor first."
        )
    else:
        opening = (
            f"Your EEG recording \"{filename}\" has been analysed by NeuroSentinel AI. "
            f"The good news is that no seizure activity was detected in this recording. "
            f"The overall risk level is {risk} with model confidence of {confidence_text}."
        )
        action = (
            "This is a reassuring result. We still recommend sharing this report with your doctor "
            "at your next scheduled visit for their review."
        )

    return f"""
<div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: 0 auto; background: #0A0A0F; color: #E8E8F0; padding: 32px; border-radius: 16px;">
    <div style="text-align: center; margin-bottom: 24px;">
        <h1 style="font-size: 20px; color: #00F0FF; margin: 0;">NeuroSentinel AI</h1>
        <p style="font-size: 11px; color: #565670; letter-spacing: 2px; text-transform: uppercase; margin-top: 4px;">EEG Analysis Report Ready</p>
    </div>

    <div style="background: rgba(255,255,255,0.04); border: 1px solid rgba(255,255,255,0.08); border-radius: 12px; padding: 20px; margin-bottom: 20px;">
        <p style="font-size: 14px; line-height: 1.7; color: #C8C8D4; margin: 0 0 16px 0;">{opening}</p>
        <p style="font-size: 14px; line-height: 1.7; color: #C8C8D4; margin: 0;">{action}</p>
    </div>

    <div style="background: rgba(0,240,255,0.06); border: 1px solid rgba(0,240,255,0.12); border-radius: 12px; padding: 16px; margin-bottom: 20px;">
        <p style="font-size: 13px; color: #00F0FF; margin: 0 0 8px 0; font-weight: 600;">Your clinical PDF report is attached to this email.</p>
        <p style="font-size: 13px; color: #C8C8D4; margin: 0;">For a more detailed AI-powered summary with health tips, dietary recommendations, and personalised guidance based on your results, open your report in the NeuroSentinel AI application.</p>
    </div>

    <div style="text-align: center; margin: 24px 0;">
        <a href="{_APP_URL}/dashboard/eeg-reports" style="display: inline-block; background: linear-gradient(135deg, #00F0FF, #818CF8); color: #0A0A0F; font-size: 13px; font-weight: 700; padding: 12px 28px; border-radius: 12px; text-decoration: none; letter-spacing: 0.5px;">View Full Report in App</a>
    </div>

    <hr style="border: none; border-top: 1px solid rgba(255,255,255,0.06); margin: 24px 0;" />

    <p style="font-size: 11px; color: #565670; text-align: center; line-height: 1.6; margin: 0;">
        This report is generated by an AI model and is intended for clinical decision support only. It does not constitute a medical diagnosis. Always consult your healthcare provider before making any medical decisions.
    </p>
</div>
"""


def _build_clinician_email(report: dict[str, Any], filename: str) -> str:
    result = report.get("result_label", "Unknown")
    risk = report.get("risk_level", "Unknown")
    event_count = report.get("event_count", 0) or 0
    confidence = report.get("confidence_score")
    confidence_text = f"{confidence:.1f}%" if isinstance(confidence, (int, float)) else "N/A"
    quality = report.get("quality_grade", "Unknown")

    return f"""
<div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: 0 auto; background: #0A0A0F; color: #E8E8F0; padding: 32px; border-radius: 16px;">
    <div style="text-align: center; margin-bottom: 24px;">
        <h1 style="font-size: 20px; color: #00F0FF; margin: 0;">NeuroSentinel AI</h1>
        <p style="font-size: 11px; color: #565670; letter-spacing: 2px; text-transform: uppercase; margin-top: 4px;">Clinical Report Notification</p>
    </div>

    <div style="background: rgba(255,255,255,0.04); border: 1px solid rgba(255,255,255,0.08); border-radius: 12px; padding: 20px; margin-bottom: 20px;">
        <table style="width: 100%; font-size: 13px; color: #C8C8D4; border-collapse: collapse;">
            <tr><td style="padding: 4px 0; color: #8888A0;">File</td><td style="padding: 4px 0; text-align: right;">{filename}</td></tr>
            <tr><td style="padding: 4px 0; color: #8888A0;">Result</td><td style="padding: 4px 0; text-align: right; font-weight: 600; color: {'#FF3366' if 'seizure' in result.lower() else '#00FF9D'};">{result}</td></tr>
            <tr><td style="padding: 4px 0; color: #8888A0;">Risk</td><td style="padding: 4px 0; text-align: right;">{risk}</td></tr>
            <tr><td style="padding: 4px 0; color: #8888A0;">Events</td><td style="padding: 4px 0; text-align: right;">{event_count}</td></tr>
            <tr><td style="padding: 4px 0; color: #8888A0;">Confidence</td><td style="padding: 4px 0; text-align: right;">{confidence_text}</td></tr>
            <tr><td style="padding: 4px 0; color: #8888A0;">Quality</td><td style="padding: 4px 0; text-align: right;">{quality}</td></tr>
        </table>
    </div>

    <p style="font-size: 13px; color: #C8C8D4; margin: 0 0 16px 0;">Clinical PDF is attached. For full structured analysis with explainability outputs, probability timelines, and SCOUT AI summary, access the report in the application.</p>

    <div style="text-align: center; margin: 24px 0;">
        <a href="{_APP_URL}/dashboard/eeg-reports" style="display: inline-block; background: linear-gradient(135deg, #00F0FF, #818CF8); color: #0A0A0F; font-size: 13px; font-weight: 700; padding: 12px 28px; border-radius: 12px; text-decoration: none; letter-spacing: 0.5px;">Open in NeuroSentinel AI</a>
    </div>

    <hr style="border: none; border-top: 1px solid rgba(255,255,255,0.06); margin: 24px 0;" />
    <p style="font-size: 11px; color: #565670; text-align: center; line-height: 1.6; margin: 0;">AI-generated report for clinical decision support. Not a standalone diagnosis. All [HEURISTIC] labels are rule-based estimates.</p>
</div>
"""


def _build_researcher_email(report: dict[str, Any], filename: str) -> str:
    result = report.get("result_label", "Unknown")
    risk = report.get("risk_level", "Unknown")
    event_count = report.get("event_count", 0) or 0
    confidence = report.get("confidence_score")
    confidence_text = f"{confidence:.1f}%" if isinstance(confidence, (int, float)) else "N/A"

    return f"""
<div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: 0 auto; background: #0A0A0F; color: #E8E8F0; padding: 32px; border-radius: 16px;">
    <div style="text-align: center; margin-bottom: 24px;">
        <h1 style="font-size: 20px; color: #00F0FF; margin: 0;">NeuroSentinel AI</h1>
        <p style="font-size: 11px; color: #565670; letter-spacing: 2px; text-transform: uppercase; margin-top: 4px;">Analysis Complete</p>
    </div>

    <div style="background: rgba(255,255,255,0.04); border: 1px solid rgba(255,255,255,0.08); border-radius: 12px; padding: 20px; margin-bottom: 20px;">
        <p style="font-size: 14px; line-height: 1.7; color: #C8C8D4; margin: 0;">
            Analysis of <strong>{filename}</strong> is complete.
            Result: {result}, risk {risk}, confidence {confidence_text}, events {event_count}.
            The clinical PDF with structured findings is attached.
        </p>
    </div>

    <p style="font-size: 13px; color: #C8C8D4; margin: 0 0 16px 0;">For the full technical breakdown — including probability timelines, channel importance rankings, attention heatmaps, band power analysis, and SCOUT AI methodology notes — open the report in the application.</p>

    <div style="text-align: center; margin: 24px 0;">
        <a href="{_APP_URL}/dashboard/eeg-reports" style="display: inline-block; background: linear-gradient(135deg, #00F0FF, #818CF8); color: #0A0A0F; font-size: 13px; font-weight: 700; padding: 12px 28px; border-radius: 12px; text-decoration: none; letter-spacing: 0.5px;">Open in NeuroSentinel AI</a>
    </div>

    <hr style="border: none; border-top: 1px solid rgba(255,255,255,0.06); margin: 24px 0;" />
    <p style="font-size: 11px; color: #565670; text-align: center; line-height: 1.6; margin: 0;">Model outputs are decision-support evidence. Cross-validate flagged segments against raw traces before drawing conclusions.</p>
</div>
"""


# ─── Email sending ─────────────────────────────────────────────────

def _build_email_html(report: dict[str, Any], filename: str, role: str | None) -> str:
    """Select the right email template based on user role."""
    role_lower = (role or "").lower()
    if role_lower == "patient":
        return _build_patient_email(report, filename)
    elif role_lower == "researcher":
        return _build_researcher_email(report, filename)
    return _build_clinician_email(report, filename)


def _get_subject(report: dict[str, Any], filename: str) -> str:
    result = report.get("result_label", "")
    event_count = report.get("event_count", 0) or 0
    seizure = result.lower() == "seizure detected" or (isinstance(event_count, int) and event_count > 0)
    if seizure:
        return _SUBJECT_SEIZURE.format(filename=filename)
    return _SUBJECT_NO_SEIZURE.format(filename=filename)


def send_report_email_resend(
    *,
    api_key: str,
    to_email: str,
    from_email: str,
    report: dict[str, Any],
    filename: str,
    role: str | None,
    pdf_bytes: bytes | None = None,
) -> bool:
    """Send report notification via Resend HTTP API."""
    subject = _get_subject(report, filename)
    html = _build_email_html(report, filename, role)

    payload: dict[str, Any] = {
        "from": from_email,
        "to": [to_email],
        "subject": subject,
        "html": html,
    }

    if pdf_bytes:
        payload["attachments"] = [
            {
                "filename": f"NeuroSentinel_Report_{filename.replace('.edf', '')}.pdf",
                "content": base64.b64encode(pdf_bytes).decode("ascii"),
                "type": "application/pdf",
            }
        ]

    try:
        response = httpx.post(
            "https://api.resend.com/emails",
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
            },
            json=payload,
            timeout=30.0,
        )
        if response.status_code in (200, 201):
            logger.info("Report email sent to %s via Resend for file %s", to_email, filename)
            return True
        logger.warning("Resend API returned %s: %s", response.status_code, response.text[:200])
        return False
    except Exception as exc:
        logger.warning("Failed to send email via Resend: %s", exc)
        return False


def send_report_email_smtp(
    *,
    smtp_host: str,
    smtp_port: int,
    smtp_user: str,
    smtp_password: str,
    from_email: str,
    to_email: str,
    report: dict[str, Any],
    filename: str,
    role: str | None,
    pdf_bytes: bytes | None = None,
    use_tls: bool = True,
) -> bool:
    """Send report notification via SMTP."""
    subject = _get_subject(report, filename)
    html = _build_email_html(report, filename, role)

    msg = MIMEMultipart("mixed")
    msg["From"] = from_email
    msg["To"] = to_email
    msg["Subject"] = subject

    html_part = MIMEText(html, "html", "utf-8")
    msg.attach(html_part)

    if pdf_bytes:
        pdf_part = MIMEApplication(pdf_bytes, _subtype="pdf")
        pdf_part.add_header(
            "Content-Disposition",
            "attachment",
            filename=f"NeuroSentinel_Report_{filename.replace('.edf', '')}.pdf",
        )
        msg.attach(pdf_part)

    try:
        if use_tls:
            server = smtplib.SMTP(smtp_host, smtp_port, timeout=30)
            server.ehlo()
            server.starttls()
            server.ehlo()
        else:
            server = smtplib.SMTP_SSL(smtp_host, smtp_port, timeout=30)

        server.login(smtp_user, smtp_password)
        server.send_message(msg)
        server.quit()
        logger.info("Report email sent to %s via SMTP (%s) for file %s", to_email, smtp_host, filename)
        return True
    except smtplib.SMTPAuthenticationError as exc:
        logger.error("SMTP authentication failed for %s — check SMTP_USER/SMTP_PASSWORD: %s", smtp_host, exc)
        return False
    except Exception as exc:
        logger.warning("Failed to send email via SMTP (%s): %s", smtp_host, exc)
        return False


def send_report_notification(
    *,
    to_email: str,
    report: dict[str, Any],
    filename: str,
    role: str | None,
    pdf_bytes: bytes | None = None,
    resend_api_key: str | None = None,
    resend_from_email: str = "NeuroSentinel AI <noreply@neurosentinel.app>",
    smtp_host: str | None = None,
    smtp_port: int = 587,
    smtp_user: str | None = None,
    smtp_password: str | None = None,
    smtp_from_email: str | None = None,
) -> bool:
    """Send report completion notification. Tries Resend first, then SMTP fallback."""
    if not to_email:
        logger.warning("No email address provided — skipping report notification.")
        return False

    # Try Resend first
    if resend_api_key:
        return send_report_email_resend(
            api_key=resend_api_key,
            to_email=to_email,
            from_email=resend_from_email,
            report=report,
            filename=filename,
            role=role,
            pdf_bytes=pdf_bytes,
        )

    # Try SMTP fallback
    if smtp_host and smtp_user and smtp_password:
        return send_report_email_smtp(
            smtp_host=smtp_host,
            smtp_port=smtp_port,
            smtp_user=smtp_user,
            smtp_password=smtp_password,
            from_email=smtp_from_email or smtp_user,
            to_email=to_email,
            report=report,
            filename=filename,
            role=role,
            pdf_bytes=pdf_bytes,
        )

    logger.info("No email provider configured (RESEND_API_KEY or SMTP_*). Skipping email notification for %s.", filename)
    return False
